### ISSUE TITLE
[임송이] 서버에서 받는 요청 query 이름 건의 사항!

### ISSUE THREAD

**Issue by Im-amberIm** [WooHyunTak/1-view-my-startup-BE-1#15]
안녕하세요~ 어제들 새벽까지 하시던데ㅜ 고생많으십니다.

지금 프론트 하고 있는데 일관성을 위해 쿼리 이름을 통일 해보는거 어떨까 싶습니다.
우현님하고 상훈님 정렬쿼리를 각 정렬기준:orderBy와 sortBy / 순서: scending과 order 이렇게 정하셨는데,
정렬기준을 sortBy(필드이름), 순서(오름/내림)을 order로 통일 하는게 어떨까요?
그리고 다른 두분은 cursor를 쓰쎴는데 저는 lastId를 써서 제가 cursor로 바꾸겠습니다.
페이지사이즈를 limit으로 사용중인데 이것도 take보다 limit으로 통일해 보는게 어떨까요?

### 정리:
- 정렬기준: sortBy=actualInvestment
- 순서: order=asc
- 데이터갯수: limit=10

- 예시: ?sortBy=actualInvestment&order=asc&limit=5?cursor=

이렇게 한번 건의 드립니다. 불필요할수도 있지만 바꾸시는게 많이 어렵지 않다면 정리 해보는거 어떨까요?
의견 궁금합니다! 혹시 제가 잘못 이해하고 있는게 있다면 알려주세요 (#순한맛으로..ㅋㅋ)

**Comment by dieuaimer** [comment]
좋은 의견입니다. 정리해주신 것과 같이 통일하는 게 좋을 것 같아요.

**Comment by WooHyunTak** [comment]
넵 위 기준으로 코드 정리 하겠습니다!!
